### ISSUE TITLE
Password of 04_bayesian_neural_networks_solution.zip

### ISSUE THREAD

**Issue by mmiakashs** [didriknielsen/ds3_abi_exercises#2]
If possible could you please share the password of this file. Thanks.

**Comment by emtiyaz** [comment]
This is given in the webpage (https://emtiyaz.github.io/teaching/ds3_2018/ds3.html), see below too. Hope this is what you need.

Exercise on Bayesian linear regression, Password for solutions (05524).
Exercise on Laplace's method, Password for solutions (86610).
Exercise on variational inference (VI), Password for solutions (00192).
Exercise on VI on Bayesian neural networks, Password for solutions (6422).

**Comment by mmiakashs** [comment]
Thanks. Sorry for the inconvenience. I didn't notice the webpage info.
